name: Windows R CMD check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  windows-check:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Check
        shell: Rscript {0}
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(
            args = c("--as-cran", "--no-manual"),
            error_on = "warning",
            check_dir = "check"
          )

      - name: Upload check artifacts
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: windows-r-cmd-check
          path: check
